apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        github:
          # The GitHub organization or user.
          owner: stefan-dalecki
          # The Github repository
          repo: argocd-example-apps
          # Reference to a Secret containing an access token. (optional)
        requeueAfterSeconds: 1800
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "guestbook-{{ .branch }}"
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
      syncPolicy:
        # Create namespace if it does not exist
        syncOptions:
          - CreateNamespace=true
          - DeleteNamespace=true
