apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbookingress
spec:
  ingressClassName: nginx
  rules:
    - host: https://kubernetes.default.svc
      http:
        paths:
          - path: /
            pathType: Prefix # pathType no longer has a default value in v1; "Exact", "Prefix", or "ImplementationSpecific" must be specified
            backend:
              service:
                name: guestbook-ui
                port:
                  number: 80
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-appset
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          # The GitHub organization or user.
          owner: stefan-dalecki
          # The Github repository
          repo: argocd-example-apps
          # Reference to a Secret containing an access token. (optional)
        requeueAfterSeconds: 1800
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      name: guestbook-ui-{{ .branch }}
      labels:
        app: guestbook-ui
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "guestbook-{{ .branch }}"
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
      syncPolicy:
        # Create namespace if it does not exist
        syncOptions:
          - CreateNamespace=true
          - DeleteNamespace=true
        managedNamespaceMetadata:
          labels:
            app.kubernetes.io/instance: guestbook-appset
